"""Rebuild corridors/east-arapahoe.js from the raw exports in "corridor data/".

Inputs (git-ignored):
    corridor data/TMC_Identification.csv        INRIX TMC geometry + lengths
    corridor data/East-Arapahoe-Road.csv        INRIX 5-min speeds per TMC
    corridor data/Statewide Crash Data/*.xlsx   CDOT statewide crash listings

Output (committed):
    corridors/east-arapahoe.js

INRIX: per-TMC day-average speed + reference (free-flow) speed on straight
start->end chords. Crashes: statewide listings buffer-filtered to the
corridor (see filter_crashes_to_corridor.py; default 250 ft).

Run from anywhere:
    python corridor-studies/scripts/build_east_arapahoe.py [--buffer-ft 250]
"""
import argparse, csv, json, os
from collections import defaultdict

from filter_crashes_to_corridor import filter_crashes

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "corridor data")
OUT = os.path.join(HERE, "..", "corridors", "east-arapahoe.js")

ap = argparse.ArgumentParser()
ap.add_argument("--buffer-ft", type=float, default=250.0)
a = ap.parse_args()

# ── INRIX: per-TMC day-average + reference speed ──────────────────────
speeds, refs = defaultdict(list), defaultdict(list)
with open(os.path.join(DATA, "East-Arapahoe-Road.csv"), newline="", encoding="utf-8-sig") as f:
    for row in csv.DictReader(f):
        try:
            speeds[row["tmc_code"]].append(float(row["speed"]))
            refs[row["tmc_code"]].append(float(row["reference_speed"]))
        except (KeyError, ValueError):
            continue

feats = []
with open(os.path.join(DATA, "TMC_Identification.csv"), newline="", encoding="utf-8-sig") as f:
    for t in csv.DictReader(f):
        tmc = t["tmc"]
        if tmc not in speeds:
            continue
        key = "EAST" if t["direction"] == "EASTBOUND" else "WEST"
        short = "EB" if key == "EAST" else "WB"
        feats.append({
            "type": "Feature",
            "geometry": {"type": "LineString", "coordinates": [
                [float(t["start_longitude"]), float(t["start_latitude"])],
                [float(t["end_longitude"]),   float(t["end_latitude"])]]},
            "properties": {
                "name": f"Arapahoe Rd @ {t['intersection']} ({short})",
                "tmc": tmc,
                "length_mi": round(float(t["miles"]), 3),
                f"speed_{key}": round(sum(speeds[tmc]) / len(speeds[tmc]), 1),
                f"freeflow_{key}": round(sum(refs[tmc]) / len(refs[tmc]), 1),
            },
        })
print(f"INRIX: {len(feats)} TMC segments")

# ── Crashes: statewide listings -> corridor buffer ────────────────────
crashes = filter_crashes(os.path.join(DATA, "TMC_Identification.csv"),
                         os.path.join(DATA, "Statewide Crash Data"),
                         a.buffer_ft)
years = sorted({c["year"] for c in crashes})
print(f"crashes: {len(crashes)} within {a.buffer_ft:.0f} ft ({years[0]}-{years[-1]})" if crashes else "crashes: none")

# ── Emit the corridor config ──────────────────────────────────────────
gj = json.dumps({"type": "FeatureCollection", "features": feats}, separators=(",", ":"))
cj = json.dumps(crashes, separators=(",", ":"))
slash2 = "/" * 2
src = (
    f"{slash2} East Arapahoe Road (CO-88), Arapahoe County CO.\n"
    f"{slash2} GENERATED by scripts/build_east_arapahoe.py - do not edit by hand.\n"
    f"{slash2} INRIX: 18 TMCs, 5-min speeds -> day mean; free-flow = INRIX reference speed.\n"
    f"{slash2} Crashes: CDOT statewide listings filtered to a {a.buffer_ft:.0f} ft corridor buffer.\n"
    f"{slash2} Raw exports live in the git-ignored 'corridor data/' folder.\n"
    "window.registerCorridor({\n"
    "  id: 'east-arapahoe',\n"
    "  name: 'East Arapahoe Road',\n"
    "  agency: 'Arapahoe County, CO',\n"
    "  center: [39.5948, -104.8447],\n"
    "  zoom: 13,\n"
    "  dirs: [\n"
    "    { key:'EAST', label:'Eastbound', short:'EB', arrow:'\\u25B6' },\n"
    "    { key:'WEST', label:'Westbound', short:'WB', arrow:'\\u25C0' }\n"
    "  ],\n"
    f"  inrix: {{ geojson: {gj} }},\n"
    f"  crashes: {cj}\n"
    "});\n"
)
with open(OUT, "w", encoding="utf-8") as f:
    f.write(src)
print(f"wrote {os.path.normpath(OUT)} ({os.path.getsize(OUT)/1024:.0f} KB)")
